### ISSUE TITLE
.js files appear outdated in master

### ISSUE THREAD

**Issue by MizzleMo** [ivogabe/gulp-typescript#124]
https://github.com/ivogabe/gulp-typescript/issues/120

Looks like the build did not generate the outputs correctly as the change shows in the .ts file, but not in the .js file for the above fix in master.

**Comment by ivogabe** [comment]
The source code is compiled into `release-2`, which is ignored by git. `gulp-typescript` is compiled using itself, so we need to have a compiled stable version of it locally. That version, "last known good", is stored in the `release` directory. The release directory isn't updated with every commit, but once in a while.

This usage of a LKG is for example also used by TypeScript.

The fix for the issue you referenced has been released in v2.7.4.
