### ISSUE TITLE
outDir seems to be ignored in the tsconfig.json file

### ISSUE THREAD

**Issue by paulvanbrenk** [ivogabe/gulp-typescript#143]
````TypeScript
{
  "compilerOptions": {
    "target": "es5", 
      "outDir": "./wwwroot/scripts"
  }
}
````

````TypeScript
var gulp = require('gulp');
var ts = require('gulp-typescript');

var proj = ts.createProject('scripts/tsconfig.json');

gulp.task('default', function () {

    var result = gulp.src('scripts/**/*.ts')
    .pipe(ts(proj));

    return result.js.pipe(gulp.dest('.'));
});
````
However after running the task the files are not in the wwwroot/scripts folder, but in the root.

**Comment by ivogabe** [comment]
I think this is related to how gulp handles files. A file path consists of 3 parts in gulp. For example we have `/root/scripts/foo.ts`. Then the cwd can be `/root`, base path `/root/scripts` and the full path is `/root/scripts/foo.ts`.

`gulp.dest` will take the full path relative to the base path (in this example `foo.ts`) and it will place that into the specified directory (thus it will be saved as `./foo.ts`).

You'd get the same behavior if you'd write this for example:
```javascript
gulp.task('default', function () {
    return gulp.src('scripts/**/*.ts')
        .pipe(gulp.dest('.'));
});
```

**Comment by paulvanbrenk** [comment]
That I understand and works as it should? However, I expected the files to be dropped in ````./wwwroot/scripts/foo.js````

**Comment by ivogabe** [comment]
The file is emitted with base path `/root/wwwroot/scripts/` and full path `/root/wwwroot/scripts/foo.js`, so the full path relative to the base path would be `./foo.js`. Using `gulp.dest('./wwwroot/scripts')` instead of `gulp.dest('.')` should work, then the file would be saved as './wwwroot/scripts/foo.js'.

It would be possible to make the base path always point to the cwd, but that would make other configurations harder. Example:
```javascript
var tsResult = gulp.src('scripts/**/*.ts')
    .pipe(ts(tsProject));

tsResult.dts.pipe(gulp.dest('release/development'))

tsResult.js
    .pipe(gulp.dest('release/development'))
    .pipe(uglify())
    .pipe(gulp.dest('release/production'));
```
When using outDir the reference paths in the declaration files are adjusted (that's the reason most people use it). If the current behavior would be changed, the javascript files would be stored under `release/development/scripts/` and `release/production/scripts/`, which obviously aren't the right places.
