### ISSUE TITLE
Shared project throws a "Could not find input file" error when using run-sequence.

### ISSUE THREAD

**Issue by jramoyo** [ivogabe/gulp-typescript#169]
When using run-sequence, a project shared between two tasks throws a "Could not find input file" error. Declaring a project as a local variable (per task) fixes the issue.

    var project = ts.createProject('tsconfig.json', {
        typescript: require('typescript')
    });

    gulp.task('_compileMain', function (done) {
        return gulp.src(config.mainTypescript)
            .pipe(ts(project))
            .js
            .pipe(gulp.dest(config.outputMainJavascriptPath));
    });

    gulp.task('_compileTest', function (done) {
        return gulp.src(config.testTypescript)
            .pipe(ts(project))
            .js
            .pipe(gulp.dest(config.outputTestJavascriptPath));
    });

    gulp.task('compile', ['_copyResources'], function (done) {
        runSequence(
            '_compileMain',
            '_compileTest',
            done);
    });

**Comment by jramoyo** [comment]
I guess the question is, should I even be sharing projects between the 2 tasks?

**Comment by ivogabe** [comment]
Using the same project in multiple tasks is indeed not working. The reason is that the project is used to store all data of the current compilation, and it thus can't be used in two different tasks at the same moment. I'll add this to the readme soon.

Is there a reason you use two tasks to compile your project? Using one will probably give a better performance as compiling the tests will also parse the main sources (for type info, assuming your tests reference or import it), so the main sources will be parsed twice. If you want to save the two sources in two different directories, you can use something like gulp-ignore after the typescript compilation.

**Comment by jramoyo** [comment]
Thanks, I will try your suggestion.
