### ISSUE TITLE
Module flag error with TypeScript 1.5

### ISSUE THREAD

**Issue by sebald** [ivogabe/gulp-typescript#171]
Hi,

When using the latest version `2.8.0` I get the following error:

```
[14:10:59] Finished 'tsc' after 6.77 ms
path/file.ts(9,1): error TS1148: Cannot compile modules unless the '--module' flag is provided.
[14:10:59] TypeScript: 1 semantic error
[14:10:59] TypeScript: emit succeeded (with errors)
```

The files get transpiled anyway. When I compile from the command line everything works fine.
I am calling `gulp-typescript` with the following options:

```json
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "module": "commonjs",
        "target": "es5",
        "removeComments": true
    }
}
```

**Comment by ivogabe** [comment]
Can you post your gulpfile?

**Comment by sebald** [comment]
Sure, here you go: https://gist.github.com/sebald/26f3bedd0197375d89a2

**Comment by ivogabe** [comment]
It looks like you're passing the whole settings object instead of the `compilerOptions` part to gulp-typescript. Changing `ts(tsconfig))` to `ts(tsconfig.compilerOptions))` would fix that. You can also use the built-in tsconfig support of gulp-typescript, as you can read [here](https://github.com/ivogabe/gulp-typescript#using-tsconfigjson)

**Comment by sebald** [comment]
Thanks! Works like a charm.
