### ISSUE TITLE
imports (TS 1.5) not working??

### ISSUE THREAD

**Issue by ceolter** [ivogabe/gulp-typescript#184]
first up, my apologies if this is not an issue, i get frustrated when people raise issues on my project when they are user error.

i'm using latest typescript for angular 2 development. when i include an import in my typscript, the resultant js file is blank. i am using gulp-typescript as follows:

```
    var tsResult = gulp
        .src('*.ts')
        .pipe(sourcemaps.init()) // for sourcemaps only
        .pipe(gulpTypescript({
            typescript: typescript,
            out: 'MyApp.js',
            target : 'es5',
            emitDecoratorMetadata: true,
            experimentalDecorators: true,
            module: 'commonjs'
        }));

    return tsResult.js
        .pipe(sourcemaps.write()) // for sourcemaps only
        .pipe(rename('MyApp.js'))
        .pipe(gulp.dest('.'));
```

i am using version 1.5.3 of typescript and the latest of gulp-typescript.

my resulting file just has the source maps, no javascript. if i remove the 'import' from the typescript, then everything works fine.

can you advise? thanks.

**Comment by ivogabe** [comment]
I think the problem is the `out` option. That option will concat all the generated JavaScript into one file, but it's only supported when you don't use (external) modules, like commonjs in your case.

When you add a `import` statement to your file, TypeScript treats it as an (external) module and the `out` option will not work any more. The generated commonjs files can't be just concatenated, but you have to use a bundler like browserify (see #166) and remove the `out` option to fix your issue.

Besides that, typescript 1.5.3 is the default compiler in gulp-typescript, so you can remove the `typescript: typescript` part as it will default to the same version.

Did this solve your problems?

**Comment by ceolter** [comment]
@ivogabe you a gentleman. that fixed it. thank you very much. :)

**Comment by ivogabe** [comment]
Glad it helped! Let me know if you run into other problems!
