### ISSUE TITLE
How to build all .js, .d.ts, and .js.map outputs from a .ts file

### ISSUE THREAD

**Issue by omidkrad** [ivogabe/gulp-typescript#220]
Hi, do you have a simple example of using `gulp-typescript` to receive a typescript file and generate all the output javascript, declaration and sourcemap files in one step or do I have to build once for each output file? Thank you.

**Comment by ivogabe** [comment]
You can combine the [source maps example](https://github.com/ivogabe/gulp-typescript#source-maps) and the second [basic example](https://github.com/ivogabe/gulp-typescript#basic-usage) to get JavaScript, definition and source map files. You can use `sourcemap.write('.')` (`'.' instead of no argument) to write definition files to a different file. You should only add `sourcemap.write()` to the JavaScript stream, not the definition stream. Can you get it working with these examples?

**Comment by omidkrad** [comment]
Not really, but I was able to get the definition file together with sourcemaps embedded in the js file. While this will work for me I guess an example of this common scenario will still be useful in the docs.

**Comment by bgrieder** [comment]
For a working example, see my comment in https://github.com/ivogabe/gulp-typescript/issues/231

**Comment by ivogabe** [comment]
I clarified the readme today, including some guidelines for source maps.
