### ISSUE TITLE
Does noExternalResolve matter?

### ISSUE THREAD

**Issue by bamoqi** [ivogabe/gulp-typescript#226]
It seems the only difference of `noExternalResolve` is whether files not read and piped from `gulp.src()` should be read by gulp-typescript into the `project.input` object when the TS compiler requests it. The speed difference seems negligible while it adds to configuration overhead. Is there a good reason why one should enable it as in your examples?

**Comment by ivogabe** [comment]
I personally see it as a good practice. It will show an error if you miss a file in the gulp.src glob. Compare it to `const` and `let` variables, instead of `const` you can always use `let`, though you will get less errors that could be useful. Besides that, you've made a good description of the option.
