### ISSUE TITLE
Make typescript peerDependency

### ISSUE THREAD

**Issue by zdychacek** [ivogabe/gulp-typescript#238]
Hi,

it would be nice, if `typescript` was moved to peerDependencies. This way it works with `tslint`and `tslint-loader`.

Thanks,

O.

**Comment by ivogabe** [comment]
Thanks for the suggestion, @zdychacek. I've been looking at this earlier. The two problems I got:

- Since npm doesn't install peerDependencies automatically, this would be a breaking change. It would be possible to do this in a new major release.
- Npm/semver seemed to have trouble with nightly versions. It's probably possible to get this working somehow.

Besides that, did you know you can already use a different version of TypeScript, including forks? See the [readme](https://github.com/ivogabe/gulp-typescript#typescript-version).
