### ISSUE TITLE
gulp-typescript >= 2.11.0 gives different src() paths from <=2.10.0

### ISSUE THREAD

**Issue by kentdotn** [ivogabe/gulp-typescript#300]
**Expected behavior:**
I have a tsconfig.json that has "files" section like following
```json
{
  "compilerOptions": { ... },
  "files": [ "path-to-directory/filename.ts" ]
}
```
and in my gulpfile.js, I invoke gulp-typescript like
```javascript
var ts = require('gulp-typescript');
...
var tsProject = ts.createProject('tsconfig.json', { sortOutput: true });
var tsResult = tsProject.src().pipe(ts(tsProject));
```
After that, the script change the path of the output *.js files to store appropriate directories.

Now, the problem I've encountered is that, when using gulp-typescript 2.10.0 or older, `src()` emits paths like 'path-to-directory/filename.ts', though, using 2.11.0 or higher, it emits './filename.ts' instead.

Is this change of path behavior intended?
If so, how should we think about src()'s output? I mean, relative paths from where?

**Comment by ivogabe** [comment]
Before 2.11, the directory of the `tsconfig.json` file was considered to be the root directory. That behavior was incorrect. In 2.11, the common directory of all files is used as the root directory, which matches the behavior of `tsc`. Thus, if you're tsconfig is located in `./` and all your files in `./lib`, and you set `outDir` to `./dest these files will be emitted as `./dest/**.js` instead of `./dest/lib/**.js`.

You can change the root directory by setting the `rootDir` compiler option in your tsconfig.json file.

**Comment by kentdotn** [comment]
Aha!
That output path is what my script do for after compilation.
Now, I can remove such renaming code. It's great!
