### ISSUE TITLE
Maintain compilation file path

### ISSUE THREAD

**Issue by zalow517** [ivogabe/gulp-typescript#306]
I'm encountering a weird issue where I need to maintain the path where the TS files are (so that the JS files are created in the same path), example:

- gulpfile.js
- tests
     - common
         - test.spec.ts

I'm trying to do this as follows:
`.pipe(gulp.dest('./'))`

But for some reason i'm having the tests created in the 'common' folder in the root of the project:

- gulpfile.js
- tests
     - common
         - test.spec.ts
- common
      - test.spec.js

Any ideas of what's happening pls?

**Comment by ivogabe** [comment]
Can you post your gulpfile and tsconfig?

**Comment by zalow517** [comment]
**gulpfile.js**

```
var typescript = require('gulp-typescript');
var gulp = require('gulp');
var exec = require('child_process').exec;

gulp.task('default', function(){
  gulp.src(['page-objects/**/*.ts','tests/**/*.ts', '!node_modules/**/*.ts'])
    .pipe(typescript())
    .pipe(gulp.dest('./')).on('end', function() {
        
        console.log('TS compilation done!');
        exec('protractor conf.js', function(err, stdout, stderr) {
            
            console.log(stdout);
            console.log(stderr);
            console.log(err);
        })
    })
});
```

I'm not using a **tsconfig** in my case. Thanks for the prompt reply!

**Comment by ivogabe** [comment]
This is because of the (sometimes unexpected) behavior of gulp. `gulp.src` sets the base property of all files to where the glob starts. For `tests/common/test.spec.ts`, that is `tests/`. gulp-typescript keeps that base property and it renames the file to`tests/common/test.spec.js`. `gulp.dest` writes files relative to their base property, resulting in `./common/test.spec.js`.

You can set the base property yourself to fix this:
```javascript
return gulp.src(['page-objects/**/*.ts','tests/**/*.ts'], { base: './' })
    ...
```
(Two nits: you don't have to exclude node_modules in your glob, since it wouldn't be included at all. Also you should return the stream from a task.)

**Comment by zalow517** [comment]
Thanks! The suggested solution worked fine. Also, thanks for the additional suggestions :)
