### ISSUE TITLE
Inconsistent output path

### ISSUE THREAD

**Issue by nicolo-ribaudo** [ivogabe/gulp-typescript#344]
Take a look at this repository: https://github.com/nicolo-ribaudo/gulp-typescript-bug (you need to run `npm install`)

If you run `gulp default`, it will generate these files
```
└── out
    ├── a
    │   └─ index.js
    └── b
        └─ b
           └─ index.js
```

Instead of
```
└── out
    ├── a
    │   └─ index.js
    └── b
        └─ index.js
```

**Comment by volodymyrlut** [comment]
+1 seen this strange issue right now.

**Comment by ivogabe** [comment]
I'm afraid that this behavior cannot be changed. Paths are resolved relative to the 'common source directory', the directory containing all source files. For project `b`, the common directory is `/`, the root of the repository. File `b/index.ts` will be emitted as `../out/b/b/index.ts`, since `outDir` is resolved to `../out/b` (relative to project root) and the filename relative to the common source directory is `b/index.ts`. That's the origin of the double `b`.

This can be fixed (for a user) on two ways:
- Don't set `outDir` and only use `gulp.dest` for setting the output directory
- Set `rootDir: "/"` and set `outDir` relative to the project root. Setting `rootDir` means that paths will be resolved relative to that directory instead of the common source directory.

**Comment by ivogabe** [comment]
This should not happen any more in version 3, since `rootDir` is now always set. In example 'b' of @nicolo-ribaudo, the compiler will now show an error, since a source file outside of the `rootDir` is passed to the compiler. See #413 and the [migration help](http://dev.ivogabe.com/gulp-typescript-3/) (section 7) for more details.
