### ISSUE TITLE
When using "gulp.watch" & "file.path" then files lose their directoy structure

### ISSUE THREAD

**Issue by bennyn** [ivogabe/gulp-typescript#354]
**Expected behavior:**

I want to compile changed TypeScript files only. These should be saved (maintaining their directory structure).

Example: `src/Greeter/HelloWorld.ts` should be compiled to `target/Greeter/HelloWorld.js`

When I use my `gulp ts` task, then it works. But if I use it in combination with `gulp.watch` it doesn't work (files will be compiled to `target` without sub-directories).

**Actual behavior:**

 `src/Greeter/HelloWorld.ts` is compiled to `target/HelloWorld.js`

**Your gulpfile:**

```javascript
var gulp = require('gulp');
var path = require('path');
var plugins = require('gulp-load-plugins')();
var tsProject = plugins.typescript.createProject('tsconfig.json');

// Loses directory structure (BUG)
gulp.task('default', function () {
  gulp.watch('src/**/*.ts').on('change', function (file) {
    gulp.src(file.path)
      .pipe(plugins.typescript(tsProject))
      .pipe(gulp.dest('target'));
  });
});

// Keeps directories & sub-directories
gulp.task('ts', function () {
  return tsProject.src()
    .pipe(plugins.typescript(tsProject))
    .pipe(gulp.dest('target'));
});
```

**tsconfig.json**

```json
{
  "compilerOptions": {
    "noEmitOnError": true,
    "noImplicitAny": true,
    "rootDir": "src"
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by bennyn** [comment]
My current workaround:

```javascript
gulp.task('default', function () {
  gulp.watch('src/script/**/*.ts').on('change', function (file) {`
    // Workaround to keep original folder structure
    var sourceDirectory = 'src';
    var currentDirectory = path.dirname(file.path);
    var index = currentDirectory.indexOf(sourceDirectory);
    var relativeDirectory = currentDirectory.slice(index + sourceDirectory.length + 1);

    gulp.src(file.path)
      .pipe(plugins.typescript(tsProject))
      .pipe(gulp.dest('dest/' + relativeDirectory));
  });
});
```

**Comment by ivogabe** [comment]
This is basically how Gulp works. When you do `gulp.src('a/b/c/d/foo.js')`, that file would have `a/b/c/d/` as base path. Gulp plugins do not change that and then `gulp.dest` writes the file, relative to that base path, to the specified folder. So `./foo.js` would be written to that directory. You can fix this by setting the `base` option in `gulp.src` to the folder that contains your source files: `gulp.src(file.path, { base: 'src/script' })`.

I do not advise you to use this approach however, since the TypeScript compiler really needs all files for the compilation. A change in one file can affect all other files. Because of that, you might get too much or too few errors about your code. If you want to speed up compilation, you should use the `isolatedModules` option. Compilation happens very fast with that option, but you do not get type errors. For developing that is no problem if your editor shows them.

**Comment by bennyn** [comment]
Hi Ivo,

Thank you very much for your detailed explanation. This throws a new 
light for me.
I will adjust my Gulp setup. I thought it would be much faster to 
compile only the changed files.

Do you know if `tsc` has already a built-in mechanism to detect changed 
files?
Because it states that it is made for JavaScript that scales. But 
compiling always all files doesn't sound like a very scalable approach 
to me.

Anyway, this issue can be closed.
Thank you so much!


Am 23.05.2016 um 17:22 schrieb Ivo Gabe de Wolff:

**Comment by ivogabe** [comment]
> Do you know if `tsc` has already a built-in mechanism to detect changed
files?

Yes, that's called incremental compilation. That's also supported by gulp-typescript, you can find more details in the [readme](https://github.com/ivogabe/gulp-typescript#incremental-compilation).
