### ISSUE TITLE
outFile option doesn't work

### ISSUE THREAD

**Issue by smartm0use** [ivogabe/gulp-typescript#379]
Hello,
i created the following gulp task:

```
gulp.task('compile', function () {
  return gulp.src(['dist/**/*.ts', 'typings/**/*.d.ts'])
    .pipe(tsCompiler({
      noImplicitAny: true,
      experimentalDecorators: true,
      outFile: 'output.js'
    }))
    .pipe(gulp.dest(paths.dist));
});
```

The output file doesn't contains my code. Here is the content:

```
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
```

If i remove the `outFile` option after compiling i get a correct Javascript file for every Typescrypt file, and all is ok.
But i would concatenate all JS into one file. So, what's wrong with `outFile` option?

**Comment by ivogabe** [comment]
Can you share your project?

**Comment by s1mp1c** [comment]
Sure, what file do you need? Here is my gulpfile: http://pastebin.com/AwK4FRuC

**Comment by smartm0use** [comment]
Hello, any news?

**Comment by ivogabe** [comment]
Haven't had time to take a look at this, though it would be useful if you could upload a whole project, or create and upload a minimal example that reproduces this problem. You can upload a .zip file on GitHub.

**Comment by smartm0use** [comment]
Here is my whole project (it is my first Angular2 app):
[myFirstApp.zip](https://github.com/ivogabe/gulp-typescript/files/381270/myFirstApp.zip)

**Comment by ivogabe** [comment]
The problem is that you cannot/should not set `outFile` when using the commonJS module system. CommonJS files cannot bundled in one file, the only thing that can be written is the `__decorate` function. `outFile` can only be used with `module: "systemjs"` or `module: "amd"`. For CommonJS modules you have to remove the `outFile` option and use webpack, browserify or rollup to bundle your files.

**Comment by gerardolima** [comment]
I am migrating one javascript application that compiles just fine with browserify. It has an entry point `app.js` with several `require` calls to load my libraries and my Angular application.

Since tsc can compile javascript files and generate a single output file, I thought I'd better remove browserify at all. The problem, though is that using `outFile` option is not changing the behavior of the `gulp-typescript` plugin: the `require` does not make the compiler to include the required module.

I can compile to the single file using tsc directly on command line, so I think that maybe it's related to the plugin.

**Comment by ivogabe** [comment]
I'm not sure what you mean, but TypeScript can (currently) not bundle commonjs files (e.g., files with `require`, `exports` and `module.exports`). It can only bundle AMD and SystemJS files, and files with no module system. So I'm not sure what tsc does, can you give some concrete example? So a small example with the source files, tsconfig, and gulpfile.

**Comment by gerardolima** [comment]
Unfortunately, I cannot share enough code, due to licence constraints. Alternatively, could you, please, suggest any Gulp setup or pattern to avoid browserify and still generating a single bundle (js+map)?

**Comment by ivogabe** [comment]
You could use [small](https://github.com/ivogabe/small), a module bundler that I wrote. It supports source maps. It's a bit experimental though. You can use it like this:

```typescript
var gulp = require('gulp');
var typescript = require('gulp-typescript');
var small = require('small').gulp;
var sourcemaps = require('gulp-sourcemaps');

var tsProject = typescript.createProject('lib/tsconfig.json');

gulp.task('compile', function() {
	return gulp.src('lib/**/*.ts')
		.pipe(sourcemaps.init())
		.pipe(typescript(tsProject))
		.pipe(small('index.js', {
			externalResolve: ['node_modules']
		}))
		.pipe(sourcemaps.write('.'))
		.pipe(gulp.dest('static/scripts'));
});
```

**Comment by gerardolima** [comment]
Thank you for your example, @ivogabe, but I think you'd understand my reluctance to integrate a experimental plugin into my build process. The Typescript compiler, itself, does this job, so I expected gulp-typescript plugin would forward this functionality.

**Comment by ivogabe** [comment]
I'm not sure what you mean with 'the typescript compiler does this job', since TypeScript does not support the combination `module: "commonjs", outFile: "..."`. gulp-typescript just passes these options to TypeScript, so that should give the same behaviour. Can you share your tsconfig file? Then I might have a better idea of what you mean.
