### ISSUE TITLE
Incremental compilation not working

### ISSUE THREAD

**Issue by felixfbecker** [ivogabe/gulp-typescript#392]
**Expected behavior:**
Only the file that changed should be compiled.

**Actual behavior:**
No matter what I try, all files are recompiled on save (verified with gulp-print). Using both a glob and `tsProject.src()`.

**Your gulpfile:**
```js
const tsProject = ts.createProject('tsconfig.json', {typescript: require('typescript')});

gulp.task('ts', () =>
    tsProject.src()
        .pipe(gulpIf(DEVELOPMENT, sourcemaps.init()))
        .pipe(print())
        .pipe(ts(tsProject)).js
        .pipe(sourcemaps.write('./', {sourceRoot: fileUrl(__dirname + '/src')}))
        .pipe(gulp.dest('dist'))

);

gulp.task('watch-ts', () =>
    gulp.watch('src/**/*.ts', ['ts'])
);
```
**tsconfig.json**

```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "declaration": false,
        "removeComments": false,
        "noLib": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "sourceMap": true,
        "pretty": true,
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "noImplicitAny": false,
        "noImplicitReturns": true,
        "noImplicitUseStrict": false,
        "noFallthroughCasesInSwitch": true,
        "rootDir": "src",
        "outDir": "dist"
    },
    "exclude": [
        "node_modules",
        "bower_components",
        "gulpfile.js",
        "dist"
    ]
}
```

**Comment by ivogabe** [comment]
I think that you got the wrong idea of what incremental compilation does. It does not compile only the changed files, but it has to compile all files again since a change of a type in one file can affect all other files. It does use some data of the previous compilation, which reduces the compilation time usually by 50%-75%. If you want more speed increase you should use `isolatedModules`, but that option will block type checking but can be useful for quick testing during development (since your IDE can probably report the type errors).

**Comment by felixfbecker** [comment]
Sorry for my misunderstanding
