### ISSUE TITLE
augmenting global scope Object fails at execution in unrelated code

### ISSUE THREAD

**Issue by gravsten** [ivogabe/gulp-typescript#397]
Since TS 2.0 it is possible to augment global scope definitions (see sample below).
Compilation works fine, without error.
But at execution in Chrome and Firefox the whole program fails in unrelated parts (imported libraries that couldn't possibly use the added functionality). Possibly the augmented definition corrupts the internals of the Javascript virtual machine.

declare global {
  interface Object {
    __testME(): any;
  }
}
Array.prototype.__testME = function() {
  return true;
}

**Comment by gravsten** [comment]
For completion, here is the exact code I wanted to use, transpiled to JS by gulp-typescript:

```
    Array.prototype.clone = Object.prototype.clone = function () {
        var out, key, val;
        out = Array.isArray(this) ? [] : {};
        for (key in this) {
            val = this[key];
            out[key] = (typeof val === 'object') ? val.clone() : val;
        }
        return out;
    };
```
It is identical to working JS code in Node.
Which makes me wonder if the browsers (here: Chrome and Firefox) have special limitations related to augmenting global scope Object ???

**Comment by ivogabe** [comment]
This does not seem to be related to gulp-typescript. Since the type definitions are not present in the generated JavaScript, that will not affect the JS runtime. So it's also not related to TypeScript. The problem might be related to the bundling of your JavaScript files for instance. Maybe you can ask this on StackOverflow or a similar website.
