### ISSUE TITLE
Version 3 doesn't output stream orderly, while the previous version can

### ISSUE THREAD

**Issue by fwang2002** [ivogabe/gulp-typescript#423]
My project depends on the order of the generated js files, and I don't want to use outFile option, but let the output js file names be listed in index.html.
The previous version can pipe the stream orderly(may not be the same order as the input of gulp.src). The order is decided by the ///\<reference ...\> in the source file, which is what I wanted.

But Version 3 keep the order the same as the input of gulp.src. So is there a bug?

**Comment by fwang2002** [comment]
I found the previous version handles Host.writeFile, which can get the correct order. While Version 3 let this method empty. It it is handled, the order can also be correct.

**Comment by ivogabe** [comment]
This has been removed to simplify the code of gulp-typescript. The code was too complex, resulting in various bugs. This was a breaking change, but that's allowed since it was in a major release.

Most people use the `outFile` option to concat the files in the correct order, or are using a module system like commonjs or AMD. I'd suggest you to move to either of these options. If that doesn't work in your situation, can you then provide some more information on your use case?

**Comment by fwang2002** [comment]
It's used only in development environment to simplify debug of code, just find the specific js file and make a breakpoint.
We don't use sourcemap, because it's hard to maintain corresponding ts source files to consist with the sourcemap when team collaboration is concerned(the code is deployed in a shared machine, and may be inconsistent with the current code base of developers) . So we just use js to debug.

I found in compiler.js the following code
```
for (var _i = 0, _a = this.host.input.getFileNames(true); _i < _a.length; _i++) {
    var fileName = _a[_i];
    var file = this.project.input.getFile(fileName);
    this.emitFile(result, currentDirectory, file);
}
```
what about change the for loop to iterate over this.host.output, like the previous version?
Or, ts2.0 has a listEmittedFiles option,  the emitted files can get from emitOutput with correct order.
It's only need to get fileName from the output array, the other processes are the same.

As I didn't look through all the code, I don't know if there are other problems.

**Comment by ivogabe** [comment]
The problem is that, when iterating over `this.host.output`, it's hard to find the corresponding input files. In v3, the loop starts with the input files and then emits only that source file so it can find the relation between input and output directly.

You could try the `includeContent ` option of gulp-sourcemaps. That will inline the sources in source maps, so the generated source files will be independent of the location of the source files. See their documentation for more information.

**Comment by fwang2002** [comment]
Thanks! I'll have a try.

**Comment by fwang2002** [comment]
And isn't this OK?
for (var fileName in this.host.output) {
    fileName = filterJsAndConvertExtToTs(fileName);
    var file = this.project.input.getFile(fileName);
    this.emitFile(result, currentDirectory, file);
}

**Comment by ivogabe** [comment]
Sorry for the late reply, I just saw that this topic was still open. The problem is that `convertExtToTs` is very complex. Version 2 contained an attempt of that strategy, but that had several issues since a lot of edge-cases existed. Basically, `outDir` complicates the process. The conversion is not only replacing `.ts` by `.js`, but also taking the `outDir` into account, which is relative to some directory, the `rootDir` or the common path of all source files etcetera. A lot of relative paths are necessary in this process, but they are all relative to a different folder.

Could you get the `includeContent` option of gulp-sourcemaps working?

**Comment by fwang2002** [comment]
I have used sourcemap, it can work, as convenient as before. Thank you!
