### ISSUE TITLE
Duplicate identifier error when using @types only in some versions of node

### ISSUE THREAD

**Issue by remojansen** [ivogabe/gulp-typescript#431]
I think this issue is probably a bug because [my config works fine in some versions of node](https://travis-ci.org/redux-bootstrap/redux-bootstrap/builds/164513204). However in some versions I get an `Duplicate identifier` error.

**Expected behavior:**
No duplicate identifier in all versions of node.

**Actual behavior:**
> /home/travis/build/redux-bootstrap/redux-bootstrap/node_modules/@types/react-redux/node_modules/@types/redux/index.d.ts(7,21): error TS2300: Duplicate identifier 'Redux'.
**Your gulpfile:**

*Include your gulpfile, or only the related task (with `ts.createProject`).*
https://github.com/remojansen/redux-bootstrap/blob/master/gulpfile.js

**tsconfig.json**
https://github.com/remojansen/redux-bootstrap/blob/master/tsconfig.json

**Comment by ivogabe** [comment]
Interesting problem. I did some investigations and it appeared that it's not the version of Node that's causing the issue, but the version of NPM. Node 4 uses NPM 2.15.9, and Node 6 uses 3.10.3 currently. They don't handle the dependencies of your dependencies the same way. Your project does not depend on `@types/redux`, but three other `@types` dependencies of yours do depend on it. NPM 2 will install this package once per dependency that uses it, resulting in three installations of `@types/redux`. Because of that, TS will show an error. NPM 3 will install this package only once, as it flattens the dependency tree. I think that you can fix this issue on node 4 by explicitly depending on `@types/redux`.

**Comment by remojansen** [comment]
Explicitly depending on `@types/redux` solved the issue. Thanks a lot for helping me out!
