### ISSUE TITLE
node_modules/gulp-typescript/typings/tsd.d.ts not found.

### ISSUE THREAD

**Issue by arg20** [ivogabe/gulp-typescript#436]
I'm using Typescript 2, to install types I just run `@types/LIBRARY_NAME`, I no longer have a typings folder, which is specially not needed since this library exports its types data.

However, this line in `release/main.d.ts(1,1)` is giving me an issue:
`/// <reference path="../typings/tsd.d.ts" />`

The module no longer has a typings folder when I install it with npm so this is referencing an inexistent folder. I get rid of that line and the error goes away. This is the error I'm seeing:

`release/main.d.ts(1,1): error TS6053: File '/Users/gabriel/work/project_one/node_modules/gulp-typescript/typings/tsd.d.ts' not found.`

**Comment by demurgos** [comment]
Hi,
I do have the same issue.

The bundled definitions should not rely on any external source. I just started to write `typings` definitions for the dependencies instead of `tsd` ones to bring scoped modules (TSD is based on globals).

It would still be great if it was possible to fix it in the meantime until the `typings` definitions are published.

**Comment by CarlosSoares** [comment]
+1

**Comment by demurgos** [comment]
Hi, I almost finished converting the project from `tsd` to `typings`, this should solve this issue.

The main issue was the missing definition for `gulp-util` so I wrote it, but it relies on the typings of `vinyl`. The definition in the registry describes an older version of `vinyl` but the update should be merged soon and I'll be able to finish the conversion.

Here are some references:
https://github.com/demurgos/typed-gulp-util
https://github.com/types/npm-vinyl/pull/1
https://github.com/typings/registry/pull/832

**Comment by ivogabe** [comment]
I'd prefer to use `@types` on npm, that would make it easier to use the type declarations. But I guess that it won't take long to switch to @types once you have updated all type declarations.

**Comment by arg20** [comment]
Hi @ivogabe, `@types` is the way to go looking forward. @demurgos If it's possible to rely on this rather it would be awesome.

**Comment by demurgos** [comment]
I am also interested in @types so I'll take a look at it. I'll submit a PR fixing this issue in the meantime, but I'll check the state of of @types.

**Comment by ivogabe** [comment]
That would be great! @types packages are genereated from the types-2.0 branch of Definitely Typed, so you should send PRs there if some definition file of a dependency is outdated.

**Comment by demurgos** [comment]
I just submitted a PR to fix the issue using `typings`. I am starting to try to use `@types`. It still seems like it might not be that stable yet. My main issue is that it does not support "decentralized" repositories yet (https://github.com/Microsoft/types-publisher/issues/4) and leads to very long delays before PR are accepted and difficulties with maintenance.

I'll let you know how it does work out.

**Comment by demurgos** [comment]
From a user perspective, `@types` is really great: I could update it really quickly and submit a new PR to use `@types` instead of `typings`.

Even if `typings` has more accurate definitions, it compiles fine with the ones from DefinitelyTyped (`@types`) so I'll just leave like this for the moment. From a definition maintainer perspective, DefinitelyTyped is still pretty painful...

**Comment by felixfbecker** [comment]
+1 for using `typings` until `@types` supports decentralized repositories.

**Comment by ivogabe** [comment]
I don't think that decentralised repositories are necessary to use `@types` here. I took the `types` branch of @demurgos and got it working after some small changes. See #448. Can someone confirm that that solves all issues related to the type definitions of gulp-typescript?

**Comment by demurgos** [comment]
Hi,
I could successfully run your branch, looks like I just made a mistake in my branch, unfortunately I wasn't then able to import it: I'm taking a look at it to give you more information.

About the decentralized repositories, I think you are right that "it works" to use `@types` as is right now. But it's a real pain to work with this. You just need to be aware that until decentralized repositories are supported, `typings` will often have better definitions because they are tested and regularly updated and reviewed: this is just impossible with the current situation of definitely-typed.

I mostly care about your module not emitting errors and keeping it "contained" (it should not mess with global variables) so in the end you can choose whatever you prefer: I'm just happy that this issue is on the way to be solved.

**Comment by ivogabe** [comment]
Version 3.1.0 now uses `@types`, so this issue is now fixed!
