### ISSUE TITLE
Q: Can I just invoke TypeScript compiler without piping?

### ISSUE THREAD

**Issue by borekb** [ivogabe/gulp-typescript#451]
Sorry for a newbie question but I'd like to use `gulp-typescript` like this (pseudocode):

```js
var tsProject = ts.createProject('tsconfig.json');
tsProject.config['include'] = ['src/**/*.ts'];
tsProject.config['compilerOptions']['outDir'] = distDir;
// ..other tsconfig.json updates for production-ready build

ts(tsProject); // this would be equivalent to just calling `tsc` on command line
```

All the examples use piping, e.g.:

```js
var tsResult = tsProject.src().pipe(tsProject());
return tsResult.js.pipe(gulp.dest('release'));
```

**Comment by ivogabe** [comment]
No, that's not possible. Gulp-typescript is a gulp plugin, so it should fit into the gulp ecosystem.

Also note that you shouldn't modify the tsProject after creating it. Instead of `tsProject.config['compilerOptions']['outDir'] = distDir;`, you can set that on the first line like `var tsProject = ts.createProject('tsconfig.json', { outDir: distDir });`. Instead of modifying `include`, you should replace `tsProject.src()` by `gulp.src('src/**/*.ts')`.

**Comment by borekb** [comment]
Thanks for the answer. Just for the record, modifying `tsProject.config` seems to work fine but I'll change the style of code to what you suggest.
