### ISSUE TITLE
TS not compiling and throwing TS2300 errors

### ISSUE THREAD

**Issue by DerKnerd** [ivogabe/gulp-typescript#524]
**Expected behavior:**
All files are compiled correctly and no error is thrown
**Actual behavior:**
Many TS2300 are thrown like the following:
```
[gulp-typescript] E:\OpenAtlas\node_modules\typescript\lib\lib.webworker.d.ts(1869,5): error TS2300 Duplicate identifier 'XMLHttpRequestResponseType'.
```
**Your gulpfile:**
*Include your gulpfile, or only the related task (with `ts.createProject`).*
```javascript
let typescript = require('gulp-typescript');
gulp.task('build-server', () => {
    let tsProject = typescript.createProject('tsconfig.json');
    let reporter = typescript.reporter.longReporter();
    let tsResult = gulp.src('./**/*.ts')
        .pipe(tsProject(reporter));
    return tsResult.js.pipe(gulp.dest('.'));
});
```

**tsconfig.json**

*Include your tsconfig, if related to this issue.*
```json
{
    "compileOnSave": true,
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2015",
        "inlineSourceMap": true,
        "removeComments": true,
        "pretty": true,
        "lib": [
            "es5",
            "es2015",
            "dom"
        ]
    }
}
```

**Comment by ivogabe** [comment]
With `gulp.src('./**/*.ts')`, you pass all TypeScript files, including those in `node_modules`. Because of this, some names are defined twice, as the standard library is added multiple times, since this is present in the TypeScript package in `node_modules`. You can fix this by using something like `gulp.src('./src/**/*.ts')` if your files are in the folder `src`.

**Comment by DerKnerd** [comment]
Yeah, that helped. Thank you a lot.
