### ISSUE TITLE
fallback to globally installed Typescript

### ISSUE THREAD

**Issue by marcelh-gh** [ivogabe/gulp-typescript#548]
While it's nice to be able to use a different version of Typesscript for each project and have gulp-typescript use that one, I think, there is a case where you have multiple projects all running on the same globally installed Typescript version.
It would be unnecessary effort to update each project as soon as there is a new Typescript version.

So, it would be nice if gulp-typescript would fall back on a globally installed Typescript if it does not find a local one for a project.

**Comment by ivogabe** [comment]
Using the global TypeScript installation does not fit well into the node & npm ecosystem. Gulp also doesn't use the global gulp-typescript installation for instance. So since you already need to install (and update) gulp-typescript locally, you can with almost the same effort install and update TypeScript locally.
