### ISSUE TITLE
downlevelIteration not supported

### ISSUE THREAD

**Issue by stryder199** [ivogabe/gulp-typescript#559]
--downlevelIteration is a listed compiler option

https://www.typescriptlang.org/docs/handbook/compiler-options.html

It seems to not be honored in gulp-typescript. I looked through the src and couldn't find any mention of it either. Is there a way to add additional commands to tsc?

**Comment by ivogabe** [comment]
`downlevelIteration` is supported, can you make sure that you are using a recent version of TypeScript and that you spelled the name correctly in your configuration? If that doesn't help, please share your gulpfile and tsconfig so we can take a look.

All options are passed to TypeScript with some exceptions that are mentioned in the readme. So we don't need to explicitly pass an option to TypeScript in gulp-typescript. That's why you can't find it in the source code of gulp-typescript.

**Comment by stryder199** [comment]
okay, thanks. I'll take another look.

**Comment by stryder199** [comment]
turned out to be an issue with es6-shim not properly exposing the Symbol.iterator for Set/Map which was causing the compiler error since I am running a full es5 environment
