### ISSUE TITLE
map files generated differ from those from tsc

### ISSUE THREAD

**Issue by bobbylight** [ivogabe/gulp-typescript#566]
I'm seeing an issue where map files generated by a gulp-typescript/gulp-ng-annotate build chain are different than those generated by tsc.  Whereas the map files appear to be OK for debugging in Chrome in both scenarios, the former build chain results in bad coverage info when using karma-coverage/karma-remap-istanbul.

I'm not sure who to point the finger at (myself, or one of the involved projects), so I'm starting here.

A very simple test app lives here:

https://github.com/bobbylight/karma-coverage-test

The readme describes how you can build locally, both with gulp-typescript/gulp-ng-annotate and tsc, run a unit test, and see map file/code coverage differences.

**Expected behavior:**
map files would match those generated by tsc.  Code coverage report generated from this build pipeline would be correct.

**Actual behavior:**
map files are different.  Specifically, the generated file (`*.js`) is included in the sources array.  Also, the relative path to the .ts file is different.  Finally, the generated mapping info is different, though I'm not sure if the differences are all due to the two "source files" or not.

Because of this, the coverage report generated by `karma-coverage` is wrong (e.g. missing coverage info for lines containing conditionals).

**Your gulpfile:**

https://github.com/bobbylight/karma-coverage-test/blob/master/gulpfile.js

**tsconfig.json**

https://github.com/bobbylight/karma-coverage-test/blob/master/tsconfig.json

**Code**

*Include your TypeScript code, if necessary.*

https://github.com/bobbylight/karma-coverage-test/blob/master/src/app/util.service.ts

**Comment by ivogabe** [comment]
The paths in the map files are different because of the way gulp-sourcemaps handles those. Recently I added some information on how to configure that in the readme, in the section "Source maps". I think that the mapping itself generated by gulp-typescript is the same as tsc. A difference might be caused by the chaining of gulp-typescript and gulp-ng-annotate. I personally have no experience with that combination.

Could you elaborate on why this breaks the coverage report of `karma-coverage`? If that was caused by wrong paths in the source maps, you could take a look at the explanation in the readme on the paths of source maps. If it is caused by the mapping itself, something might go wrong in the chaining of the two gulp plugins.

**Comment by bobbylight** [comment]
Sorry for the late reply.  I couldn't pin down what specifically was breaking things.  If I manually "fixed" the paths in the source map (or lcov file generated by karma-coverage), the coverage report was still wrong.  Line numbers/offsets weren't wrong, but certain constructs - for example, if/while conditionals, of calls to `Array.push()` simply had no coverage info (not flagged as hit, partially hit, or missed).  Because of this, it definitely seemed like the coverage data was incomplete somehow.  It also leads me to suspect gulp-ngannotate/gulp-sourcemaps as opposed to this package.

I worked around this by having our production build first build without running ngAnnotate and running our unit test suite against that output (thus the coverage report uploaded to Sonar is correct).  Then I rebuild, this time with ngAnnotate.  Far from ideal, but the build is relatively quick.

**Comment by ivogabe** [comment]
Are you still interested in this issue?
