### ISSUE TITLE
Does gulp-typescript play nice with Visual Studio?

### ISSUE THREAD

**Issue by johnnyreilly** [ivogabe/gulp-typescript#65]
Hi people!

I've just stumbled upon gulp-typescript as I was looking into some gulp related continuous release stuff.

This looks really interesting - my question is: is this only intended to be used outside of Visual Studio?  Or if not, how does it fit in when used inside Visual Studio?  Do you need to prevent VS from performing the compilation perhaps?

I think it might be beneficial (perhaps not only to me :smile:) to enhance the readme.md to clarify this....

**Comment by ivogabe** [comment]
You can use this with Visual Studio, but you need to make sure VS won't compile the .ts files. I don't know exactly how you should do that.. You can use windows power shell for example to run `gulp`, or maybe a gulp extension in Visual Studio, I don't know whether that exists.

I can add this to the readme if this solves your questions.

**Comment by xt0rted** [comment]
Using the [Task Runner Explorer](https://visualstudiogallery.msdn.microsoft.com/8e1b4368-4afb-467a-bc13-9650572db708), [Grunt Launcher](https://visualstudiogallery.msdn.microsoft.com/dcbc5325-79ef-4b72-960e-0a51ee33a0ff), and [Package Intellisense](https://visualstudiogallery.msdn.microsoft.com/65748cdb-4087-497e-a394-2e3449c8e61e) extensions should give you everything you need to work almost entirely in VS2013 (this is all built in to 2015). And if you need to use the command line then the [Open Command Line](https://visualstudiogallery.msdn.microsoft.com/4e84e2cf-2d6b-472a-b1e2-b84932511379) extension makes that a bit easier as well.

If you start using a setup like this you'll need to update all of your typescript files so their Build Action is set to `Content`. This is because even when `Compile on save` is disabled (project properties > typescript build) msbuild will continue to compile the files on each build. It's probably easiest to edit the project file directly and find & replace `TypeScriptCompile` to `Content`.

I'm not sure if this was unique to my setup or not but I'd recommend not running gulp as a post build step and instead do something like run [gulp-watch](https://www.npmjs.com/package/gulp-watch) on startup or from a console. When running gulp post build with F5 I found the site would start to load before gulp finished and then my css & js would return 404s.

**Comment by johnnyreilly** [comment]
Thanks for the pointers. I'm already using gulp for js minification and concatenation with task runner extension. Was wondering about getting the TS compilation in the mix too.

Do you lose intellisense when you switch to content files? That'd be a blocker for me.

**Comment by xt0rted** [comment]
I have ReSharper installed but I've disabled js & ts support since it doesn't support `require()` or ts1.4 so I'm using the built-in tooling and I'm getting IntelliSense in my gulpfile and typescript files just fine.

**Comment by johnnyreilly** [comment]
Nice. (I've also disabled resharper for the same reasons)

**Comment by ivogabe** [comment]
See Microsoft/TypeScript#2326 for a proposal to make it easier to use gulp & Visual Studio together.

**Comment by johnnyreilly** [comment]
Thanks for the pointer @ivogabe

**Comment by ivogabe** [comment]
I'd advise everyone to use the new [Visual Studio Code](https://code.visualstudio.com), which support typescript & gulp out of the box. It's also available for mac & linux.

For the normal Visual Studio users, this page from grunt-ts might be useful: [How to disable the Visual Studio TypeScript build](https://github.com/TypeStrong/grunt-ts/blob/master/docs/DisableVisualStudioBuild.md).

**Comment by meffect** [comment]
Use the command line, conemu, cygwin ex: http://superuser.com/questions/473807/%D0%A1onemu-how-do-i-make-several-console-windows-in-one-tab-from-task-file/900232#900232

IDE integration only leads to frustration and missed opportunity. Use gulp-watch and some proper terminal configuration and bliss

**Comment by netdragonboberb** [comment]
I followed the instructions above, and it sorta worked, but I can't debug breakpoints in .ts files. I can set them, but they don't do anything. I am not using grunt-ts, just gulp (with gulp set up in Task Runner). Has anyone had problems with breakpoints?

**Comment by netdragonboberb** [comment]
See also <TypeScriptCompileBlocked> .csproj option (I think it also works in .njsproj files) from https://github.com/Microsoft/TypeScript/issues/2326  to stick after Microsoft.TypeScript.targets Example:
<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.targets" Condition="False" />
<PropertyGroup>
		<TypeScriptCompileBlocked>True</TypeScriptCompileBlocked>
		<TypescriptCompileOnSaveEnabled>False</TypescriptCompileOnSaveEnabled>
</PropertyGroup>

**Comment by meziantou** [comment]
I wrote a guide to replace the default compilation of TypeScript files in Visual Studio by Gulp: https://www.meziantou.net/2017/10/23/compiling-typescript-using-gulp-in-visual-studio
