### ISSUE TITLE
gulp-watch bug?

### ISSUE THREAD

**Issue by tugend** [ivogabe/gulp-typescript#82]
Hi, 

I have a setup where I use gulp-watch like so:

```
        watch(glob)
            ... \\ A
            .pipe(typescript({ module: 'commonjs'}))
            ... \\ B
            .pipe(gulp.dest(dir));
```

Everything works fine in (A) but nothing gets through the pipe with typescript to (B).
Gulp.watch is not enough for my case and I'm stumped as to why this should not work with gulp-watch. 

I have other identical targets using different gulp compilers which work fine. Can you confirm or reject the issue? 

Cheers =)

**Comment by ivogabe** [comment]
That's probably because of the way gulp-watch is designed: gulp-watch is an endless stream. gulp-typescript needs to have all the files before it can start compilation, since files contain types that other files are using, thus it waits for the `end` event. gulp-watch doesn't emit that event, since a stream can only emit that once, and it needs to push new files to the stream if something changes. The only solution would be to not use gulp-watch here.

Why are you using gulp-watch here? gulp-typescript needs to have all files, not just the ones that are changed, because unchanged files contain type info that TypeScript needs to know, so you probably don't want to pass only the changed files to gulp-typescript.

**Comment by tugend** [comment]
Fair enough thanks for the explanation! I guess that makes sense.

I am moving from a setup where I compiled coffeescript files,
and after the initial compile step, I used to just compile the changed files.

I was using gulp-watch to add a filter that caught delted source files and made sure the corresponding output files where deleted too. 

Thank you. <(")
