### ISSUE TITLE
[npm3] Check TypeScript (peerDependency || explicit dependency)

### ISSUE THREAD

**Issue by fredgalvao** [ivogabe/gulp-typescript#84]
We might wanna make sure **typescript** is always installed, which means migrating it to an explicit dependency on a near future. I might be wrong if typescript isn't directly used BY gulp-typescript, but instead WITH gulp-typescript when installed, and if that's the case this issue can be closed right away.

As of **npm@2.7.1**, I get the following warning when installing **gulp-typescript**:

```
npm WARN peerDependencies | The peer dependency typescript@>=1.4.1 <2.0.0 included from gulp-typescript will no
npm WARN peerDependencies | longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies | in npm 3+. Your application will need to depend on it explicitly.
```

More details about the change can be found [here](http://blog.npmjs.org/post/110924823920/npm-weekly-5) or at npm/npm#6565.

**Comment by ivogabe** [comment]
It's possible to bring your own version of TypeScript. See #63. Because of that, typescript needed to be a peerDependency. A normal dependency doesn't work, since the user-installed version of typescript might be shadowed by the default version (the one that gulp-typescript installed). That's why I switched typescript to a peerDependency. As of npm 3, that isn't working anymore, the user is forced to add TypeScript as a dependency. I think there are two possible solutions:

1 - force users to add TypeScript to their package.json.
Pros: Flexibility
Cons: Extra work to update, since you need to update 2 dependencies.

2 - Switch back to normal dependency, force users to write some extra code in their gulp file:
```
[...].pipe(typescript({
  typescript: require('typescript')
})
```
That is already supported (to use gulp-typescript with typescript forks). The require in the gulpfile will resolve to the installation of typescript of the user, thus allowing a different version.

My vote would be for option two, so the normal users don't have to change anything.

@whitneyit What do you think?

**Comment by fredgalvao** [comment]
peerDependencies will not "stop working" as of npm 3, they just aquired a different behaviour.

If the **typescript** dependency(library) isn't `require()`'d nor used directly on **gulp-typescript**, it can keep living as a peerDependency, otherwise one of the mentioned alternative solutions will have to be.

**Comment by ivogabe** [comment]
Yes, I got that. typescript is used by gulp-typescript, gulp-typescript doesn't work without it. But gulp-typescript allows users to choose a typescript version. Because of that, typescript is currently a peerDependency. But most users just want to use the latest stable release. The old behavior would install typescript always, the new behavior forces all users to add typescript to their package.json file if I understand correctly. The question is: should we force normal users to add typescript as a dependency or should we force other users to write extra code for a different typescript version?

**Comment by fredgalvao** [comment]
I guess that's something up to dependency managemet, not actual code. I'd vote for the first option then.

**Comment by whitneyit** [comment]
I'd argue that the second option is clearer. Instead of having typescript
appear to magically be resolved within `gulp-typescript` it is clear that
the user is stating *use this one*.

It addresses questions like:
* Is it using its own version?
* My global version?
* That version I just installed locally?

That being said both options will require updating of code. The second
option seems like the changes can be localised to the `tsProject` Object.

This way if someone wants to use one global install everywhere they can.

**Comment by mikehaas763** [comment]
@ivogabe I'm usually for explicitness, so I'd argue that option two is the obvious and simplest approach. Isn't it possible to have both options? If no valid typescript module is pass in on the 'typescript' property then attempt to load one from the consuming packages node_modules? I don't use nodejs on a daily basis so I'm not sure if there are any inherent problems with that.

**Comment by ivogabe** [comment]
I've implemented option 2
